<?php
/**
 * Created by PhpStorm.
 * User: Itzcy
 * Date: 2018/2/19
 * Time: 19:05
 */

namespace app\index\controller;


use app\common\controller\Init;

class Base extends Init
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}