<?php
/**
 * Created by PhpStorm.
 * User: Itzcy
 * Date: 2018/2/19
 * Time: 19:05
 */

namespace app\index\controller;


use app\common\controller\Init;
use app\index\model\SysConfig;
use think\exception\DbException;
use think\facade\App;
use think\facade\Config;
use think\facade\Request;
use think\facade\Cache;
use think\facade\View;
use think\response\Redirect;

/**
 * 基础处理器 其他需集成
 * Class Base
 * @package app\index\controller
 */
abstract class Base extends Init
{
    /**
     * 系统配置
     * @var array
     */
    protected $sysConfig;

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub

        View::assign('module', Request::module());
        View::assign('controller', Request::controller());
        View::assign('action', Request::action());

        $this->loadSysConfig();

        View::assign('sysConfig', $this->sysConfig);

        // 修改默认模版的位置目录
//        define('DS', DIRECTORY_SEPARATOR);

//        $theme = 'default';

//        Config::set('template.view_path', '..'.DS.'template' . DS . $theme . DS);
//        Config::set('template.view_base', '..'.DS.'template' . DS . $theme . DS);
//        // 修改静态文件目录替换
//        Config::set('template.tpl_replace_string', ['__CDN_STATIC__' => '/static/template/' . $theme]);

    }

    /**
     * 从数据库加载配置文件
     */
    private function loadSysConfig()
    {
        try {
            $sysConfig = SysConfig::cache('sys_config')->field(['k', 'v'])->select();
            foreach ($sysConfig as $itme) {
                $this->sysConfig[$itme['k']] = $itme['v'];
            }
        } catch (DbException $e) {
            trace($e->getTraceAsString(), 'EXCEPTION');
        }
    }


    public function _empty()
    {
        return Redirect::create('/', 'redirect');
    }

}