<?php
/**
 * Created by PhpStorm.
 * User: Itzcy
 * Date: 2018/4/13
 * Time: 23:30
 */

namespace app\wechat\controller;


use EasyWeChat\Factory;
use EasyWeChat\OfficialAccount\Application;
use think\Controller;
use think\Log;
use think\facade\Request;

class Msgapi extends Controller
{
    /**
     * @var Application
     */
    protected $wechatApp;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this -> wechatApp = Factory::officialAccount(config('wechat.wechat'));
    }

    public function index()
    {
        // 按消息类型分发请求
        $this -> wechatApp -> server -> push(function($message) {
            $msgType = $message['MsgType'];
            $module = Request::module();
            $logic = 'app\\' . $module . '\\wechatmsg\\' . ucfirst($msgType);
            if (class_exists($logic)) {
                return $logic::deal($message);
            } else {
                return '';
            }
        });
        return $this -> wechatApp -> server -> serve() -> send();
    }

}