<?php
/**
 * Created by PhpStorm.
 * User: Itzcy
 * Date: 2018/4/13
 * Time: 23:30
 */

namespace app\wechat\controller;


use EasyWeChat\Factory;
use EasyWeChat\OfficialAccount\Application;
use think\Controller;
use think\Log;
use think\Request;

class Msgapi extends Controller
{
    /**
     * @var Application
     */
    protected $app;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> app = Factory::officialAccount(config('wechat.wechat'));
    }

    public function index()
    {
        // 按消息类型分发请求
        $this -> app -> server -> push(function($message) {
            $msgType = $message['MsgType'];
            $module = Request::instance()->module();
            $logic = 'app\\' . $module . '\\wechatmsg\\' . ucfirst($msgType);
            if (class_exists($logic)) {
                return $logic::deal($message);
            } else {
                $itPk = $this -> getItPk($message);
                return $itPk;
            }
        });
        $this -> app -> server -> serve() -> send();
    }

    private function getItPk($message)
    {
        $requestUrl = 'http://i.itpk.cn/api.php?question='.$message['Content'].'&api_key=e67b8359f04d016f61f2be1d95ae4f16&api_secret=6l5ee9ona1nx';
        $ch = curl_init($requestUrl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);
        return $output;
    }

}