<?php
/**
 * Created by PhpStorm.
 * User: itzcy
 * Date: 17-8-11
 * Time: 下午4:09
 */
namespace app\dashboard\controller;

use app\dashboard\controller\Base;
use think\Request;

class Error extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        return $this -> fetch('public/404');

    }
}