<?php
/**
 * Created by PhpStorm.
 * User: Itzcy
 * Date: 2017/7/30
 * Time: 22:53
 */
namespace app\dashboard\controller;

use system\SystemInfo;

class Index extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登陆后的框架页
     * @return mixed
     */
    public function index()
    {
        $count['artNum'] = model('article') -> where([]) -> count();
        $count['clsNum'] = model('category') -> where([]) -> count();
        $count['userNum'] = model('sys_manage') -> where([]) -> count();
        $count['likNum'] = model('links') -> where([]) -> count();
        
        $this -> assign('count', $count);
        return view();
    }

    /**
     * 欢迎页
     */
    public function welcome()
    {
        // 获取系统信息
        $sysInfo = SystemInfo::getSystemInfo();
        // 获取框架信息
        $framInfo = $this -> getFrameworkInfo();
        // 获取监控信息
        $monitorInfo =SystemInfo::getMonitorInfo();
        $this -> assign([
            'sysInfo' => $sysInfo, // 操作系统系统信息
            'framInfo' => $framInfo, // 框架信息
            'monitorInfo' => $monitorInfo // 监控信息
        ]);
        return view();
    }
}
